### ISSUE TITLE
dry-monads listed twice in projects

### ISSUE THREAD

**Issue by paul** [dry-rb/devtools#1]
https://github.com/dry-rb/devtools/blob/d315c96a1a9f45b2dd0761ee0f12206ca11f367a/projects#L12-L13

Perhaps this is why dry-monitor wasn't updated recently, and why CodeClimate is failing my other PR? dry-rb/dry-monitor#32

**Comment by flash-gordon** [comment]
No, it's because dry-monitor is not managed by devtools yet. Two dry-monads lines is a leftover from my recent changes. Should I connect dry-monitor @solnic ?

**Comment by solnic** [comment]
@flash-gordon yeah my intention was to connect all dry-rb gems. I missed dry-monitor accidentally.
